# @package _global_
defaults:
  - wandb: defaults
  - _self_

seed: 1234
data_dir: ../data

n_init_labeled: 20 # Number of init labeled samples. Default 10000
n_query: 1 # Number of queries per round. Default 1000
n_round: 300 # Number of rounds. Default 10
dataset_name: CINIC10 # "MNIST", "FashionMNIST", "SVHN", "CIFAR10" "CINIC10"
strategy_name: DropoutPnml #  "DropoutPnml", "SingleLayerPnml",  "RandomSampling", "LeastConfidence", "MarginSampling", "EntropySampling", "LeastConfidenceDropout", "MarginSamplingDropout", "EntropySamplingDropout", "KMeansSampling", "KCenterGreedy", "BALDDropout", "AdversarialBIM", "AdversarialDeepFool",
validation_set_size: 1024

# Active learning inference
n_drop: 10
unlabeled_batch_size: 256
unlabeled_pool_size: 1024
test_batch_size: 256
test_set_size: 1024

# Optimization
max_epochs: 300
min_epochs: 1
batch_size: 64
batch_size_test: 512
gradient_clip_val: 1.0
num_workers: 0
lr: 0.001
momentum: 0.9
weight_decay: 1e-4
early_stopping_patience: 5
lr_scheduler_patience: 3
dropout: 0.5
precision: 32

hydra:
  job:
    chdir: True
  run:
    dir: ../outputs/${dataset_name}_${strategy_name}_${now:%Y%m%d_%H%M%S}
