# @package _global_
defaults:
  - wandb: defaults
  - _self_

seed: 1234
data_dir: ../data

n_init_labeled: 150 # Number of init labeled samples. Default 10000
n_query: 1 # Number of queries per round. Default 1000
n_round: 300 # Number of rounds. Default 10
dataset_name: MNIST_OOD # "MNIST", "MNIST_OOD", "EMNIST", "FashionMNIST", "SVHN", "CIFAR10" "CINIC10"
strategy_name: DropoutPnml #  "DropoutPnml", DropoutGenie "SingleLayerPnml",  "RandomSampling", "LeastConfidence", "MarginSampling", "EntropySampling", "LeastConfidenceDropout", "MarginSamplingDropout", "EntropySamplingDropout", "KMeansSampling", "KCenterGreedy", "BALDDropout", "AdversarialBIM", "AdversarialDeepFool",
val_set_size: 1024
dataset_limit: 10000 # Reduce raw dataset size to fit into GPU

# Active learning inference
n_drop: 10
query_batch_size: 256
unlabeled_pool_size: 255
test_set_size: 512

# Optimization
max_epochs: 300
min_epochs: 1
batch_size: 64
batch_size_test: 512
gradient_clip_val: 1.0
num_workers: 0
lr: 0.001
momentum: 0.9
weight_decay: 1e-2
early_stopping_patience: 10
reduce_on_plature_patience: 3
dropout: 0.5
precision: 16

hydra:
  job:
    chdir: True
  run:
    dir: ../outputs/${dataset_name}_${strategy_name}_${now:%Y%m%d_%H%M%S}
