# @package _global_
defaults:
  - wandb: defaults
  - _self_

seed: 1234
data_dir: ../data

n_init_labeled: 100 # Number of init labeled samples. Default 10000
n_query: 1 # Number of queries per round. Default 1000
n_round: 3000 # Number of rounds. Default 10
training_set_size: 1024 # Number of training (labeled and unlabeled) -1 for all
validation_set_size: 1024 # Validation set size
dataset_name: MNIST # "MNIST", "FashionMNIST", "SVHN", "CIFAR10"
strategy_name: SingleLayerPnml #  SingleLayerPnml,  "RandomSampling", "LeastConfidence", "MarginSampling", "EntropySampling", "LeastConfidenceDropout", "MarginSamplingDropout", "EntropySamplingDropout", "KMeansSampling", "KCenterGreedy", "BALDDropout", "AdversarialBIM", "AdversarialDeepFool",

SingleLayerPnml:
  unlabeled_batch_size: 36
  unlabeled_pool_size: 1024

epochs_max: 50
epochs_min: 50
batch_size: 64
batch_size_test: 2048
gradient_clip_val: 0.5
num_workers: 0
lr: 0.1
milestones: [20, 45]
momentum: 0.9
weight_decay: 1e-4

date: ${now:%Y%m%d_%H}

hydra:
  job:
    chdir: True
  run:
    dir: ../outputs/${dataset_name}_${strategy_name}_${now:%Y%m%d_%H%M%S}
